/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LibraryUserRouteImport } from './routes/library-user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublisherIndexRouteImport } from './routes/publisher/index'
import { Route as PbAdminIndexRouteImport } from './routes/pb-admin/index'
import { Route as LibraryAdminIndexRouteImport } from './routes/library-admin/index'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as PublisherSupportRouteImport } from './routes/publisher/support'
import { Route as PublisherSettingsRouteImport } from './routes/publisher/settings'
import { Route as PublisherSalesReportRouteImport } from './routes/publisher/sales-report'
import { Route as PublisherProfileRouteImport } from './routes/publisher/profile'
import { Route as PublisherMarginReportRouteImport } from './routes/publisher/margin-report'
import { Route as PublisherBankAccountsRouteImport } from './routes/publisher/bank-accounts'
import { Route as PbAdminSalesReportRouteImport } from './routes/pb-admin/sales-report'
import { Route as PbAdminPublishersAuthorsRouteImport } from './routes/pb-admin/publishers-authors'
import { Route as PbAdminPromoCodesRouteImport } from './routes/pb-admin/promo-codes'
import { Route as PbAdminMergeAuthorsRouteImport } from './routes/pb-admin/merge-authors'
import { Route as PbAdminMarginReportRouteImport } from './routes/pb-admin/margin-report'
import { Route as PbAdminCustomersRouteImport } from './routes/pb-admin/customers'
import { Route as PbAdminCommissionRatesRouteImport } from './routes/pb-admin/commission-rates'
import { Route as PbAdminCategoriesRouteImport } from './routes/pb-admin/categories'
import { Route as PbAdminAuthorManagementRouteImport } from './routes/pb-admin/author-management'
import { Route as PbAdminAdminUsersRouteImport } from './routes/pb-admin/admin-users'
import { Route as LibraryAdminUsersRouteImport } from './routes/library-admin/users'
import { Route as LibraryAdminSupportRouteImport } from './routes/library-admin/support'
import { Route as LibraryAdminRequestsRouteImport } from './routes/library-admin/requests'
import { Route as LibraryAdminReportsRouteImport } from './routes/library-admin/reports'
import { Route as LibraryAdminOrdersRouteImport } from './routes/library-admin/orders'
import { Route as LibraryAdminManageEbooksRouteImport } from './routes/library-admin/manage-ebooks'
import { Route as LibraryAdminDepartmentsRouteImport } from './routes/library-admin/departments'
import { Route as LibraryAdminCoursesRouteImport } from './routes/library-admin/courses'
import { Route as LibraryAdminCatalogueRouteImport } from './routes/library-admin/catalogue'
import { Route as LibraryAdminCartRouteImport } from './routes/library-admin/cart'
import { Route as LibraryAdminBannersRouteImport } from './routes/library-admin/banners'
import { Route as PublisherPromoCodesIndexRouteImport } from './routes/publisher/promo-codes.index'
import { Route as PublisherCatalogueIndexRouteImport } from './routes/publisher/catalogue.index'
import { Route as PublisherCatalogueImportIndexRouteImport } from './routes/publisher/catalogue-import.index'
import { Route as PublisherBundlesIndexRouteImport } from './routes/publisher/bundles.index'
import { Route as PbAdminTitlesIndexRouteImport } from './routes/pb-admin/titles.index'
import { Route as PbAdminBundlesIndexRouteImport } from './routes/pb-admin/bundles.index'
import { Route as PublisherPromoCodesNewRouteImport } from './routes/publisher/promo-codes.new'
import { Route as PublisherCatalogueNewRouteImport } from './routes/publisher/catalogue.new'
import { Route as PublisherCatalogueBookIdRouteImport } from './routes/publisher/catalogue.$bookId'
import { Route as PublisherCatalogueImportNewRouteImport } from './routes/publisher/catalogue-import.new'
import { Route as PublisherCatalogueImportFileNameRouteImport } from './routes/publisher/catalogue-import.$fileName'
import { Route as PublisherBundlesNewRouteImport } from './routes/publisher/bundles.new'
import { Route as PublisherBundlesBundleIdRouteImport } from './routes/publisher/bundles.$bundleId'
import { Route as PbAdminTitlesNewRouteImport } from './routes/pb-admin/titles.new'
import { Route as PbAdminTitlesBookIdRouteImport } from './routes/pb-admin/titles.$bookId'
import { Route as PbAdminPublishersAuthorsIdRouteImport } from './routes/pb-admin/publishers-authors.$id'
import { Route as PbAdminCommissionRatesIdRouteImport } from './routes/pb-admin/commission-rates_/$id'
import { Route as PbAdminBundlesNewRouteImport } from './routes/pb-admin/bundles.new'
import { Route as PbAdminBundlesBundleIdRouteImport } from './routes/pb-admin/bundles.$bundleId'
import { Route as PbAdminAuthorManagementAuthorIdRouteImport } from './routes/pb-admin/author-management.$authorId'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryUserRoute = LibraryUserRouteImport.update({
  id: '/library-user',
  path: '/library-user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherIndexRoute = PublisherIndexRouteImport.update({
  id: '/publisher/',
  path: '/publisher/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminIndexRoute = PbAdminIndexRouteImport.update({
  id: '/pb-admin/',
  path: '/pb-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminIndexRoute = LibraryAdminIndexRouteImport.update({
  id: '/library-admin/',
  path: '/library-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSupportRoute = PublisherSupportRouteImport.update({
  id: '/publisher/support',
  path: '/publisher/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSettingsRoute = PublisherSettingsRouteImport.update({
  id: '/publisher/settings',
  path: '/publisher/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSalesReportRoute = PublisherSalesReportRouteImport.update({
  id: '/publisher/sales-report',
  path: '/publisher/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherProfileRoute = PublisherProfileRouteImport.update({
  id: '/publisher/profile',
  path: '/publisher/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherMarginReportRoute = PublisherMarginReportRouteImport.update({
  id: '/publisher/margin-report',
  path: '/publisher/margin-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherBankAccountsRoute = PublisherBankAccountsRouteImport.update({
  id: '/publisher/bank-accounts',
  path: '/publisher/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminSalesReportRoute = PbAdminSalesReportRouteImport.update({
  id: '/pb-admin/sales-report',
  path: '/pb-admin/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminPublishersAuthorsRoute =
  PbAdminPublishersAuthorsRouteImport.update({
    id: '/pb-admin/publishers-authors',
    path: '/pb-admin/publishers-authors',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminPromoCodesRoute = PbAdminPromoCodesRouteImport.update({
  id: '/pb-admin/promo-codes',
  path: '/pb-admin/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminMergeAuthorsRoute = PbAdminMergeAuthorsRouteImport.update({
  id: '/pb-admin/merge-authors',
  path: '/pb-admin/merge-authors',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminMarginReportRoute = PbAdminMarginReportRouteImport.update({
  id: '/pb-admin/margin-report',
  path: '/pb-admin/margin-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCustomersRoute = PbAdminCustomersRouteImport.update({
  id: '/pb-admin/customers',
  path: '/pb-admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCommissionRatesRoute = PbAdminCommissionRatesRouteImport.update({
  id: '/pb-admin/commission-rates',
  path: '/pb-admin/commission-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCategoriesRoute = PbAdminCategoriesRouteImport.update({
  id: '/pb-admin/categories',
  path: '/pb-admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAuthorManagementRoute = PbAdminAuthorManagementRouteImport.update({
  id: '/pb-admin/author-management',
  path: '/pb-admin/author-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAdminUsersRoute = PbAdminAdminUsersRouteImport.update({
  id: '/pb-admin/admin-users',
  path: '/pb-admin/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminUsersRoute = LibraryAdminUsersRouteImport.update({
  id: '/library-admin/users',
  path: '/library-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminSupportRoute = LibraryAdminSupportRouteImport.update({
  id: '/library-admin/support',
  path: '/library-admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminRequestsRoute = LibraryAdminRequestsRouteImport.update({
  id: '/library-admin/requests',
  path: '/library-admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminReportsRoute = LibraryAdminReportsRouteImport.update({
  id: '/library-admin/reports',
  path: '/library-admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminOrdersRoute = LibraryAdminOrdersRouteImport.update({
  id: '/library-admin/orders',
  path: '/library-admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminManageEbooksRoute =
  LibraryAdminManageEbooksRouteImport.update({
    id: '/library-admin/manage-ebooks',
    path: '/library-admin/manage-ebooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryAdminDepartmentsRoute = LibraryAdminDepartmentsRouteImport.update({
  id: '/library-admin/departments',
  path: '/library-admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminCoursesRoute = LibraryAdminCoursesRouteImport.update({
  id: '/library-admin/courses',
  path: '/library-admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminCatalogueRoute = LibraryAdminCatalogueRouteImport.update({
  id: '/library-admin/catalogue',
  path: '/library-admin/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminCartRoute = LibraryAdminCartRouteImport.update({
  id: '/library-admin/cart',
  path: '/library-admin/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminBannersRoute = LibraryAdminBannersRouteImport.update({
  id: '/library-admin/banners',
  path: '/library-admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPromoCodesIndexRoute =
  PublisherPromoCodesIndexRouteImport.update({
    id: '/publisher/promo-codes/',
    path: '/publisher/promo-codes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueIndexRoute = PublisherCatalogueIndexRouteImport.update({
  id: '/publisher/catalogue/',
  path: '/publisher/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherCatalogueImportIndexRoute =
  PublisherCatalogueImportIndexRouteImport.update({
    id: '/publisher/catalogue-import/',
    path: '/publisher/catalogue-import/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherBundlesIndexRoute = PublisherBundlesIndexRouteImport.update({
  id: '/publisher/bundles/',
  path: '/publisher/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminTitlesIndexRoute = PbAdminTitlesIndexRouteImport.update({
  id: '/pb-admin/titles/',
  path: '/pb-admin/titles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminBundlesIndexRoute = PbAdminBundlesIndexRouteImport.update({
  id: '/pb-admin/bundles/',
  path: '/pb-admin/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPromoCodesNewRoute = PublisherPromoCodesNewRouteImport.update({
  id: '/publisher/promo-codes/new',
  path: '/publisher/promo-codes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherCatalogueNewRoute = PublisherCatalogueNewRouteImport.update({
  id: '/publisher/catalogue/new',
  path: '/publisher/catalogue/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherCatalogueBookIdRoute =
  PublisherCatalogueBookIdRouteImport.update({
    id: '/publisher/catalogue/$bookId',
    path: '/publisher/catalogue/$bookId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueImportNewRoute =
  PublisherCatalogueImportNewRouteImport.update({
    id: '/publisher/catalogue-import/new',
    path: '/publisher/catalogue-import/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueImportFileNameRoute =
  PublisherCatalogueImportFileNameRouteImport.update({
    id: '/publisher/catalogue-import/$fileName',
    path: '/publisher/catalogue-import/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherBundlesNewRoute = PublisherBundlesNewRouteImport.update({
  id: '/publisher/bundles/new',
  path: '/publisher/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherBundlesBundleIdRoute =
  PublisherBundlesBundleIdRouteImport.update({
    id: '/publisher/bundles/$bundleId',
    path: '/publisher/bundles/$bundleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminTitlesNewRoute = PbAdminTitlesNewRouteImport.update({
  id: '/pb-admin/titles/new',
  path: '/pb-admin/titles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminTitlesBookIdRoute = PbAdminTitlesBookIdRouteImport.update({
  id: '/pb-admin/titles/$bookId',
  path: '/pb-admin/titles/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminPublishersAuthorsIdRoute =
  PbAdminPublishersAuthorsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PbAdminPublishersAuthorsRoute,
  } as any)
const PbAdminCommissionRatesIdRoute =
  PbAdminCommissionRatesIdRouteImport.update({
    id: '/pb-admin/commission-rates_/$id',
    path: '/pb-admin/commission-rates/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminBundlesNewRoute = PbAdminBundlesNewRouteImport.update({
  id: '/pb-admin/bundles/new',
  path: '/pb-admin/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminBundlesBundleIdRoute = PbAdminBundlesBundleIdRouteImport.update({
  id: '/pb-admin/bundles/$bundleId',
  path: '/pb-admin/bundles/$bundleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAuthorManagementAuthorIdRoute =
  PbAdminAuthorManagementAuthorIdRouteImport.update({
    id: '/$authorId',
    path: '/$authorId',
    getParentRoute: () => PbAdminAuthorManagementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library-user': typeof LibraryUserRoute
  '/notifications': typeof NotificationsRoute
  '/library-admin/banners': typeof LibraryAdminBannersRoute
  '/library-admin/cart': typeof LibraryAdminCartRoute
  '/library-admin/catalogue': typeof LibraryAdminCatalogueRoute
  '/library-admin/courses': typeof LibraryAdminCoursesRoute
  '/library-admin/departments': typeof LibraryAdminDepartmentsRoute
  '/library-admin/manage-ebooks': typeof LibraryAdminManageEbooksRoute
  '/library-admin/orders': typeof LibraryAdminOrdersRoute
  '/library-admin/reports': typeof LibraryAdminReportsRoute
  '/library-admin/requests': typeof LibraryAdminRequestsRoute
  '/library-admin/support': typeof LibraryAdminSupportRoute
  '/library-admin/users': typeof LibraryAdminUsersRoute
  '/pb-admin/admin-users': typeof PbAdminAdminUsersRoute
  '/pb-admin/author-management': typeof PbAdminAuthorManagementRouteWithChildren
  '/pb-admin/categories': typeof PbAdminCategoriesRoute
  '/pb-admin/commission-rates': typeof PbAdminCommissionRatesRoute
  '/pb-admin/customers': typeof PbAdminCustomersRoute
  '/pb-admin/margin-report': typeof PbAdminMarginReportRoute
  '/pb-admin/merge-authors': typeof PbAdminMergeAuthorsRoute
  '/pb-admin/promo-codes': typeof PbAdminPromoCodesRoute
  '/pb-admin/publishers-authors': typeof PbAdminPublishersAuthorsRouteWithChildren
  '/pb-admin/sales-report': typeof PbAdminSalesReportRoute
  '/publisher/bank-accounts': typeof PublisherBankAccountsRoute
  '/publisher/margin-report': typeof PublisherMarginReportRoute
  '/publisher/profile': typeof PublisherProfileRoute
  '/publisher/sales-report': typeof PublisherSalesReportRoute
  '/publisher/settings': typeof PublisherSettingsRoute
  '/publisher/support': typeof PublisherSupportRoute
  '/author/': typeof AuthorIndexRoute
  '/library-admin/': typeof LibraryAdminIndexRoute
  '/pb-admin/': typeof PbAdminIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/pb-admin/author-management/$authorId': typeof PbAdminAuthorManagementAuthorIdRoute
  '/pb-admin/bundles/$bundleId': typeof PbAdminBundlesBundleIdRoute
  '/pb-admin/bundles/new': typeof PbAdminBundlesNewRoute
  '/pb-admin/commission-rates/$id': typeof PbAdminCommissionRatesIdRoute
  '/pb-admin/publishers-authors/$id': typeof PbAdminPublishersAuthorsIdRoute
  '/pb-admin/titles/$bookId': typeof PbAdminTitlesBookIdRoute
  '/pb-admin/titles/new': typeof PbAdminTitlesNewRoute
  '/publisher/bundles/$bundleId': typeof PublisherBundlesBundleIdRoute
  '/publisher/bundles/new': typeof PublisherBundlesNewRoute
  '/publisher/catalogue-import/$fileName': typeof PublisherCatalogueImportFileNameRoute
  '/publisher/catalogue-import/new': typeof PublisherCatalogueImportNewRoute
  '/publisher/catalogue/$bookId': typeof PublisherCatalogueBookIdRoute
  '/publisher/catalogue/new': typeof PublisherCatalogueNewRoute
  '/publisher/promo-codes/new': typeof PublisherPromoCodesNewRoute
  '/pb-admin/bundles/': typeof PbAdminBundlesIndexRoute
  '/pb-admin/titles/': typeof PbAdminTitlesIndexRoute
  '/publisher/bundles/': typeof PublisherBundlesIndexRoute
  '/publisher/catalogue-import/': typeof PublisherCatalogueImportIndexRoute
  '/publisher/catalogue/': typeof PublisherCatalogueIndexRoute
  '/publisher/promo-codes/': typeof PublisherPromoCodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library-user': typeof LibraryUserRoute
  '/notifications': typeof NotificationsRoute
  '/library-admin/banners': typeof LibraryAdminBannersRoute
  '/library-admin/cart': typeof LibraryAdminCartRoute
  '/library-admin/catalogue': typeof LibraryAdminCatalogueRoute
  '/library-admin/courses': typeof LibraryAdminCoursesRoute
  '/library-admin/departments': typeof LibraryAdminDepartmentsRoute
  '/library-admin/manage-ebooks': typeof LibraryAdminManageEbooksRoute
  '/library-admin/orders': typeof LibraryAdminOrdersRoute
  '/library-admin/reports': typeof LibraryAdminReportsRoute
  '/library-admin/requests': typeof LibraryAdminRequestsRoute
  '/library-admin/support': typeof LibraryAdminSupportRoute
  '/library-admin/users': typeof LibraryAdminUsersRoute
  '/pb-admin/admin-users': typeof PbAdminAdminUsersRoute
  '/pb-admin/author-management': typeof PbAdminAuthorManagementRouteWithChildren
  '/pb-admin/categories': typeof PbAdminCategoriesRoute
  '/pb-admin/commission-rates': typeof PbAdminCommissionRatesRoute
  '/pb-admin/customers': typeof PbAdminCustomersRoute
  '/pb-admin/margin-report': typeof PbAdminMarginReportRoute
  '/pb-admin/merge-authors': typeof PbAdminMergeAuthorsRoute
  '/pb-admin/promo-codes': typeof PbAdminPromoCodesRoute
  '/pb-admin/publishers-authors': typeof PbAdminPublishersAuthorsRouteWithChildren
  '/pb-admin/sales-report': typeof PbAdminSalesReportRoute
  '/publisher/bank-accounts': typeof PublisherBankAccountsRoute
  '/publisher/margin-report': typeof PublisherMarginReportRoute
  '/publisher/profile': typeof PublisherProfileRoute
  '/publisher/sales-report': typeof PublisherSalesReportRoute
  '/publisher/settings': typeof PublisherSettingsRoute
  '/publisher/support': typeof PublisherSupportRoute
  '/author': typeof AuthorIndexRoute
  '/library-admin': typeof LibraryAdminIndexRoute
  '/pb-admin': typeof PbAdminIndexRoute
  '/publisher': typeof PublisherIndexRoute
  '/pb-admin/author-management/$authorId': typeof PbAdminAuthorManagementAuthorIdRoute
  '/pb-admin/bundles/$bundleId': typeof PbAdminBundlesBundleIdRoute
  '/pb-admin/bundles/new': typeof PbAdminBundlesNewRoute
  '/pb-admin/commission-rates/$id': typeof PbAdminCommissionRatesIdRoute
  '/pb-admin/publishers-authors/$id': typeof PbAdminPublishersAuthorsIdRoute
  '/pb-admin/titles/$bookId': typeof PbAdminTitlesBookIdRoute
  '/pb-admin/titles/new': typeof PbAdminTitlesNewRoute
  '/publisher/bundles/$bundleId': typeof PublisherBundlesBundleIdRoute
  '/publisher/bundles/new': typeof PublisherBundlesNewRoute
  '/publisher/catalogue-import/$fileName': typeof PublisherCatalogueImportFileNameRoute
  '/publisher/catalogue-import/new': typeof PublisherCatalogueImportNewRoute
  '/publisher/catalogue/$bookId': typeof PublisherCatalogueBookIdRoute
  '/publisher/catalogue/new': typeof PublisherCatalogueNewRoute
  '/publisher/promo-codes/new': typeof PublisherPromoCodesNewRoute
  '/pb-admin/bundles': typeof PbAdminBundlesIndexRoute
  '/pb-admin/titles': typeof PbAdminTitlesIndexRoute
  '/publisher/bundles': typeof PublisherBundlesIndexRoute
  '/publisher/catalogue-import': typeof PublisherCatalogueImportIndexRoute
  '/publisher/catalogue': typeof PublisherCatalogueIndexRoute
  '/publisher/promo-codes': typeof PublisherPromoCodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library-user': typeof LibraryUserRoute
  '/notifications': typeof NotificationsRoute
  '/library-admin/banners': typeof LibraryAdminBannersRoute
  '/library-admin/cart': typeof LibraryAdminCartRoute
  '/library-admin/catalogue': typeof LibraryAdminCatalogueRoute
  '/library-admin/courses': typeof LibraryAdminCoursesRoute
  '/library-admin/departments': typeof LibraryAdminDepartmentsRoute
  '/library-admin/manage-ebooks': typeof LibraryAdminManageEbooksRoute
  '/library-admin/orders': typeof LibraryAdminOrdersRoute
  '/library-admin/reports': typeof LibraryAdminReportsRoute
  '/library-admin/requests': typeof LibraryAdminRequestsRoute
  '/library-admin/support': typeof LibraryAdminSupportRoute
  '/library-admin/users': typeof LibraryAdminUsersRoute
  '/pb-admin/admin-users': typeof PbAdminAdminUsersRoute
  '/pb-admin/author-management': typeof PbAdminAuthorManagementRouteWithChildren
  '/pb-admin/categories': typeof PbAdminCategoriesRoute
  '/pb-admin/commission-rates': typeof PbAdminCommissionRatesRoute
  '/pb-admin/customers': typeof PbAdminCustomersRoute
  '/pb-admin/margin-report': typeof PbAdminMarginReportRoute
  '/pb-admin/merge-authors': typeof PbAdminMergeAuthorsRoute
  '/pb-admin/promo-codes': typeof PbAdminPromoCodesRoute
  '/pb-admin/publishers-authors': typeof PbAdminPublishersAuthorsRouteWithChildren
  '/pb-admin/sales-report': typeof PbAdminSalesReportRoute
  '/publisher/bank-accounts': typeof PublisherBankAccountsRoute
  '/publisher/margin-report': typeof PublisherMarginReportRoute
  '/publisher/profile': typeof PublisherProfileRoute
  '/publisher/sales-report': typeof PublisherSalesReportRoute
  '/publisher/settings': typeof PublisherSettingsRoute
  '/publisher/support': typeof PublisherSupportRoute
  '/author/': typeof AuthorIndexRoute
  '/library-admin/': typeof LibraryAdminIndexRoute
  '/pb-admin/': typeof PbAdminIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/pb-admin/author-management/$authorId': typeof PbAdminAuthorManagementAuthorIdRoute
  '/pb-admin/bundles/$bundleId': typeof PbAdminBundlesBundleIdRoute
  '/pb-admin/bundles/new': typeof PbAdminBundlesNewRoute
  '/pb-admin/commission-rates_/$id': typeof PbAdminCommissionRatesIdRoute
  '/pb-admin/publishers-authors/$id': typeof PbAdminPublishersAuthorsIdRoute
  '/pb-admin/titles/$bookId': typeof PbAdminTitlesBookIdRoute
  '/pb-admin/titles/new': typeof PbAdminTitlesNewRoute
  '/publisher/bundles/$bundleId': typeof PublisherBundlesBundleIdRoute
  '/publisher/bundles/new': typeof PublisherBundlesNewRoute
  '/publisher/catalogue-import/$fileName': typeof PublisherCatalogueImportFileNameRoute
  '/publisher/catalogue-import/new': typeof PublisherCatalogueImportNewRoute
  '/publisher/catalogue/$bookId': typeof PublisherCatalogueBookIdRoute
  '/publisher/catalogue/new': typeof PublisherCatalogueNewRoute
  '/publisher/promo-codes/new': typeof PublisherPromoCodesNewRoute
  '/pb-admin/bundles/': typeof PbAdminBundlesIndexRoute
  '/pb-admin/titles/': typeof PbAdminTitlesIndexRoute
  '/publisher/bundles/': typeof PublisherBundlesIndexRoute
  '/publisher/catalogue-import/': typeof PublisherCatalogueImportIndexRoute
  '/publisher/catalogue/': typeof PublisherCatalogueIndexRoute
  '/publisher/promo-codes/': typeof PublisherPromoCodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library-user'
    | '/notifications'
    | '/library-admin/banners'
    | '/library-admin/cart'
    | '/library-admin/catalogue'
    | '/library-admin/courses'
    | '/library-admin/departments'
    | '/library-admin/manage-ebooks'
    | '/library-admin/orders'
    | '/library-admin/reports'
    | '/library-admin/requests'
    | '/library-admin/support'
    | '/library-admin/users'
    | '/pb-admin/admin-users'
    | '/pb-admin/author-management'
    | '/pb-admin/categories'
    | '/pb-admin/commission-rates'
    | '/pb-admin/customers'
    | '/pb-admin/margin-report'
    | '/pb-admin/merge-authors'
    | '/pb-admin/promo-codes'
    | '/pb-admin/publishers-authors'
    | '/pb-admin/sales-report'
    | '/publisher/bank-accounts'
    | '/publisher/margin-report'
    | '/publisher/profile'
    | '/publisher/sales-report'
    | '/publisher/settings'
    | '/publisher/support'
    | '/author/'
    | '/library-admin/'
    | '/pb-admin/'
    | '/publisher/'
    | '/pb-admin/author-management/$authorId'
    | '/pb-admin/bundles/$bundleId'
    | '/pb-admin/bundles/new'
    | '/pb-admin/commission-rates/$id'
    | '/pb-admin/publishers-authors/$id'
    | '/pb-admin/titles/$bookId'
    | '/pb-admin/titles/new'
    | '/publisher/bundles/$bundleId'
    | '/publisher/bundles/new'
    | '/publisher/catalogue-import/$fileName'
    | '/publisher/catalogue-import/new'
    | '/publisher/catalogue/$bookId'
    | '/publisher/catalogue/new'
    | '/publisher/promo-codes/new'
    | '/pb-admin/bundles/'
    | '/pb-admin/titles/'
    | '/publisher/bundles/'
    | '/publisher/catalogue-import/'
    | '/publisher/catalogue/'
    | '/publisher/promo-codes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library-user'
    | '/notifications'
    | '/library-admin/banners'
    | '/library-admin/cart'
    | '/library-admin/catalogue'
    | '/library-admin/courses'
    | '/library-admin/departments'
    | '/library-admin/manage-ebooks'
    | '/library-admin/orders'
    | '/library-admin/reports'
    | '/library-admin/requests'
    | '/library-admin/support'
    | '/library-admin/users'
    | '/pb-admin/admin-users'
    | '/pb-admin/author-management'
    | '/pb-admin/categories'
    | '/pb-admin/commission-rates'
    | '/pb-admin/customers'
    | '/pb-admin/margin-report'
    | '/pb-admin/merge-authors'
    | '/pb-admin/promo-codes'
    | '/pb-admin/publishers-authors'
    | '/pb-admin/sales-report'
    | '/publisher/bank-accounts'
    | '/publisher/margin-report'
    | '/publisher/profile'
    | '/publisher/sales-report'
    | '/publisher/settings'
    | '/publisher/support'
    | '/author'
    | '/library-admin'
    | '/pb-admin'
    | '/publisher'
    | '/pb-admin/author-management/$authorId'
    | '/pb-admin/bundles/$bundleId'
    | '/pb-admin/bundles/new'
    | '/pb-admin/commission-rates/$id'
    | '/pb-admin/publishers-authors/$id'
    | '/pb-admin/titles/$bookId'
    | '/pb-admin/titles/new'
    | '/publisher/bundles/$bundleId'
    | '/publisher/bundles/new'
    | '/publisher/catalogue-import/$fileName'
    | '/publisher/catalogue-import/new'
    | '/publisher/catalogue/$bookId'
    | '/publisher/catalogue/new'
    | '/publisher/promo-codes/new'
    | '/pb-admin/bundles'
    | '/pb-admin/titles'
    | '/publisher/bundles'
    | '/publisher/catalogue-import'
    | '/publisher/catalogue'
    | '/publisher/promo-codes'
  id:
    | '__root__'
    | '/'
    | '/library-user'
    | '/notifications'
    | '/library-admin/banners'
    | '/library-admin/cart'
    | '/library-admin/catalogue'
    | '/library-admin/courses'
    | '/library-admin/departments'
    | '/library-admin/manage-ebooks'
    | '/library-admin/orders'
    | '/library-admin/reports'
    | '/library-admin/requests'
    | '/library-admin/support'
    | '/library-admin/users'
    | '/pb-admin/admin-users'
    | '/pb-admin/author-management'
    | '/pb-admin/categories'
    | '/pb-admin/commission-rates'
    | '/pb-admin/customers'
    | '/pb-admin/margin-report'
    | '/pb-admin/merge-authors'
    | '/pb-admin/promo-codes'
    | '/pb-admin/publishers-authors'
    | '/pb-admin/sales-report'
    | '/publisher/bank-accounts'
    | '/publisher/margin-report'
    | '/publisher/profile'
    | '/publisher/sales-report'
    | '/publisher/settings'
    | '/publisher/support'
    | '/author/'
    | '/library-admin/'
    | '/pb-admin/'
    | '/publisher/'
    | '/pb-admin/author-management/$authorId'
    | '/pb-admin/bundles/$bundleId'
    | '/pb-admin/bundles/new'
    | '/pb-admin/commission-rates_/$id'
    | '/pb-admin/publishers-authors/$id'
    | '/pb-admin/titles/$bookId'
    | '/pb-admin/titles/new'
    | '/publisher/bundles/$bundleId'
    | '/publisher/bundles/new'
    | '/publisher/catalogue-import/$fileName'
    | '/publisher/catalogue-import/new'
    | '/publisher/catalogue/$bookId'
    | '/publisher/catalogue/new'
    | '/publisher/promo-codes/new'
    | '/pb-admin/bundles/'
    | '/pb-admin/titles/'
    | '/publisher/bundles/'
    | '/publisher/catalogue-import/'
    | '/publisher/catalogue/'
    | '/publisher/promo-codes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryUserRoute: typeof LibraryUserRoute
  NotificationsRoute: typeof NotificationsRoute
  LibraryAdminBannersRoute: typeof LibraryAdminBannersRoute
  LibraryAdminCartRoute: typeof LibraryAdminCartRoute
  LibraryAdminCatalogueRoute: typeof LibraryAdminCatalogueRoute
  LibraryAdminCoursesRoute: typeof LibraryAdminCoursesRoute
  LibraryAdminDepartmentsRoute: typeof LibraryAdminDepartmentsRoute
  LibraryAdminManageEbooksRoute: typeof LibraryAdminManageEbooksRoute
  LibraryAdminOrdersRoute: typeof LibraryAdminOrdersRoute
  LibraryAdminReportsRoute: typeof LibraryAdminReportsRoute
  LibraryAdminRequestsRoute: typeof LibraryAdminRequestsRoute
  LibraryAdminSupportRoute: typeof LibraryAdminSupportRoute
  LibraryAdminUsersRoute: typeof LibraryAdminUsersRoute
  PbAdminAdminUsersRoute: typeof PbAdminAdminUsersRoute
  PbAdminAuthorManagementRoute: typeof PbAdminAuthorManagementRouteWithChildren
  PbAdminCategoriesRoute: typeof PbAdminCategoriesRoute
  PbAdminCommissionRatesRoute: typeof PbAdminCommissionRatesRoute
  PbAdminCustomersRoute: typeof PbAdminCustomersRoute
  PbAdminMarginReportRoute: typeof PbAdminMarginReportRoute
  PbAdminMergeAuthorsRoute: typeof PbAdminMergeAuthorsRoute
  PbAdminPromoCodesRoute: typeof PbAdminPromoCodesRoute
  PbAdminPublishersAuthorsRoute: typeof PbAdminPublishersAuthorsRouteWithChildren
  PbAdminSalesReportRoute: typeof PbAdminSalesReportRoute
  PublisherBankAccountsRoute: typeof PublisherBankAccountsRoute
  PublisherMarginReportRoute: typeof PublisherMarginReportRoute
  PublisherProfileRoute: typeof PublisherProfileRoute
  PublisherSalesReportRoute: typeof PublisherSalesReportRoute
  PublisherSettingsRoute: typeof PublisherSettingsRoute
  PublisherSupportRoute: typeof PublisherSupportRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  LibraryAdminIndexRoute: typeof LibraryAdminIndexRoute
  PbAdminIndexRoute: typeof PbAdminIndexRoute
  PublisherIndexRoute: typeof PublisherIndexRoute
  PbAdminBundlesBundleIdRoute: typeof PbAdminBundlesBundleIdRoute
  PbAdminBundlesNewRoute: typeof PbAdminBundlesNewRoute
  PbAdminCommissionRatesIdRoute: typeof PbAdminCommissionRatesIdRoute
  PbAdminTitlesBookIdRoute: typeof PbAdminTitlesBookIdRoute
  PbAdminTitlesNewRoute: typeof PbAdminTitlesNewRoute
  PublisherBundlesBundleIdRoute: typeof PublisherBundlesBundleIdRoute
  PublisherBundlesNewRoute: typeof PublisherBundlesNewRoute
  PublisherCatalogueImportFileNameRoute: typeof PublisherCatalogueImportFileNameRoute
  PublisherCatalogueImportNewRoute: typeof PublisherCatalogueImportNewRoute
  PublisherCatalogueBookIdRoute: typeof PublisherCatalogueBookIdRoute
  PublisherCatalogueNewRoute: typeof PublisherCatalogueNewRoute
  PublisherPromoCodesNewRoute: typeof PublisherPromoCodesNewRoute
  PbAdminBundlesIndexRoute: typeof PbAdminBundlesIndexRoute
  PbAdminTitlesIndexRoute: typeof PbAdminTitlesIndexRoute
  PublisherBundlesIndexRoute: typeof PublisherBundlesIndexRoute
  PublisherCatalogueImportIndexRoute: typeof PublisherCatalogueImportIndexRoute
  PublisherCatalogueIndexRoute: typeof PublisherCatalogueIndexRoute
  PublisherPromoCodesIndexRoute: typeof PublisherPromoCodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-user': {
      id: '/library-user'
      path: '/library-user'
      fullPath: '/library-user'
      preLoaderRoute: typeof LibraryUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/': {
      id: '/publisher/'
      path: '/publisher'
      fullPath: '/publisher/'
      preLoaderRoute: typeof PublisherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/': {
      id: '/pb-admin/'
      path: '/pb-admin'
      fullPath: '/pb-admin/'
      preLoaderRoute: typeof PbAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/': {
      id: '/library-admin/'
      path: '/library-admin'
      fullPath: '/library-admin/'
      preLoaderRoute: typeof LibraryAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/support': {
      id: '/publisher/support'
      path: '/publisher/support'
      fullPath: '/publisher/support'
      preLoaderRoute: typeof PublisherSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/settings': {
      id: '/publisher/settings'
      path: '/publisher/settings'
      fullPath: '/publisher/settings'
      preLoaderRoute: typeof PublisherSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/sales-report': {
      id: '/publisher/sales-report'
      path: '/publisher/sales-report'
      fullPath: '/publisher/sales-report'
      preLoaderRoute: typeof PublisherSalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/profile': {
      id: '/publisher/profile'
      path: '/publisher/profile'
      fullPath: '/publisher/profile'
      preLoaderRoute: typeof PublisherProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/margin-report': {
      id: '/publisher/margin-report'
      path: '/publisher/margin-report'
      fullPath: '/publisher/margin-report'
      preLoaderRoute: typeof PublisherMarginReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bank-accounts': {
      id: '/publisher/bank-accounts'
      path: '/publisher/bank-accounts'
      fullPath: '/publisher/bank-accounts'
      preLoaderRoute: typeof PublisherBankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/sales-report': {
      id: '/pb-admin/sales-report'
      path: '/pb-admin/sales-report'
      fullPath: '/pb-admin/sales-report'
      preLoaderRoute: typeof PbAdminSalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/publishers-authors': {
      id: '/pb-admin/publishers-authors'
      path: '/pb-admin/publishers-authors'
      fullPath: '/pb-admin/publishers-authors'
      preLoaderRoute: typeof PbAdminPublishersAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/promo-codes': {
      id: '/pb-admin/promo-codes'
      path: '/pb-admin/promo-codes'
      fullPath: '/pb-admin/promo-codes'
      preLoaderRoute: typeof PbAdminPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/merge-authors': {
      id: '/pb-admin/merge-authors'
      path: '/pb-admin/merge-authors'
      fullPath: '/pb-admin/merge-authors'
      preLoaderRoute: typeof PbAdminMergeAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/margin-report': {
      id: '/pb-admin/margin-report'
      path: '/pb-admin/margin-report'
      fullPath: '/pb-admin/margin-report'
      preLoaderRoute: typeof PbAdminMarginReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/customers': {
      id: '/pb-admin/customers'
      path: '/pb-admin/customers'
      fullPath: '/pb-admin/customers'
      preLoaderRoute: typeof PbAdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/commission-rates': {
      id: '/pb-admin/commission-rates'
      path: '/pb-admin/commission-rates'
      fullPath: '/pb-admin/commission-rates'
      preLoaderRoute: typeof PbAdminCommissionRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/categories': {
      id: '/pb-admin/categories'
      path: '/pb-admin/categories'
      fullPath: '/pb-admin/categories'
      preLoaderRoute: typeof PbAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/author-management': {
      id: '/pb-admin/author-management'
      path: '/pb-admin/author-management'
      fullPath: '/pb-admin/author-management'
      preLoaderRoute: typeof PbAdminAuthorManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/admin-users': {
      id: '/pb-admin/admin-users'
      path: '/pb-admin/admin-users'
      fullPath: '/pb-admin/admin-users'
      preLoaderRoute: typeof PbAdminAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/users': {
      id: '/library-admin/users'
      path: '/library-admin/users'
      fullPath: '/library-admin/users'
      preLoaderRoute: typeof LibraryAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/support': {
      id: '/library-admin/support'
      path: '/library-admin/support'
      fullPath: '/library-admin/support'
      preLoaderRoute: typeof LibraryAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/requests': {
      id: '/library-admin/requests'
      path: '/library-admin/requests'
      fullPath: '/library-admin/requests'
      preLoaderRoute: typeof LibraryAdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/reports': {
      id: '/library-admin/reports'
      path: '/library-admin/reports'
      fullPath: '/library-admin/reports'
      preLoaderRoute: typeof LibraryAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/orders': {
      id: '/library-admin/orders'
      path: '/library-admin/orders'
      fullPath: '/library-admin/orders'
      preLoaderRoute: typeof LibraryAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/manage-ebooks': {
      id: '/library-admin/manage-ebooks'
      path: '/library-admin/manage-ebooks'
      fullPath: '/library-admin/manage-ebooks'
      preLoaderRoute: typeof LibraryAdminManageEbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/departments': {
      id: '/library-admin/departments'
      path: '/library-admin/departments'
      fullPath: '/library-admin/departments'
      preLoaderRoute: typeof LibraryAdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/courses': {
      id: '/library-admin/courses'
      path: '/library-admin/courses'
      fullPath: '/library-admin/courses'
      preLoaderRoute: typeof LibraryAdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/catalogue': {
      id: '/library-admin/catalogue'
      path: '/library-admin/catalogue'
      fullPath: '/library-admin/catalogue'
      preLoaderRoute: typeof LibraryAdminCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/cart': {
      id: '/library-admin/cart'
      path: '/library-admin/cart'
      fullPath: '/library-admin/cart'
      preLoaderRoute: typeof LibraryAdminCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/banners': {
      id: '/library-admin/banners'
      path: '/library-admin/banners'
      fullPath: '/library-admin/banners'
      preLoaderRoute: typeof LibraryAdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/promo-codes/': {
      id: '/publisher/promo-codes/'
      path: '/publisher/promo-codes'
      fullPath: '/publisher/promo-codes/'
      preLoaderRoute: typeof PublisherPromoCodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue/': {
      id: '/publisher/catalogue/'
      path: '/publisher/catalogue'
      fullPath: '/publisher/catalogue/'
      preLoaderRoute: typeof PublisherCatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue-import/': {
      id: '/publisher/catalogue-import/'
      path: '/publisher/catalogue-import'
      fullPath: '/publisher/catalogue-import/'
      preLoaderRoute: typeof PublisherCatalogueImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bundles/': {
      id: '/publisher/bundles/'
      path: '/publisher/bundles'
      fullPath: '/publisher/bundles/'
      preLoaderRoute: typeof PublisherBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/titles/': {
      id: '/pb-admin/titles/'
      path: '/pb-admin/titles'
      fullPath: '/pb-admin/titles/'
      preLoaderRoute: typeof PbAdminTitlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/bundles/': {
      id: '/pb-admin/bundles/'
      path: '/pb-admin/bundles'
      fullPath: '/pb-admin/bundles/'
      preLoaderRoute: typeof PbAdminBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/promo-codes/new': {
      id: '/publisher/promo-codes/new'
      path: '/publisher/promo-codes/new'
      fullPath: '/publisher/promo-codes/new'
      preLoaderRoute: typeof PublisherPromoCodesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue/new': {
      id: '/publisher/catalogue/new'
      path: '/publisher/catalogue/new'
      fullPath: '/publisher/catalogue/new'
      preLoaderRoute: typeof PublisherCatalogueNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue/$bookId': {
      id: '/publisher/catalogue/$bookId'
      path: '/publisher/catalogue/$bookId'
      fullPath: '/publisher/catalogue/$bookId'
      preLoaderRoute: typeof PublisherCatalogueBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue-import/new': {
      id: '/publisher/catalogue-import/new'
      path: '/publisher/catalogue-import/new'
      fullPath: '/publisher/catalogue-import/new'
      preLoaderRoute: typeof PublisherCatalogueImportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue-import/$fileName': {
      id: '/publisher/catalogue-import/$fileName'
      path: '/publisher/catalogue-import/$fileName'
      fullPath: '/publisher/catalogue-import/$fileName'
      preLoaderRoute: typeof PublisherCatalogueImportFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bundles/new': {
      id: '/publisher/bundles/new'
      path: '/publisher/bundles/new'
      fullPath: '/publisher/bundles/new'
      preLoaderRoute: typeof PublisherBundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bundles/$bundleId': {
      id: '/publisher/bundles/$bundleId'
      path: '/publisher/bundles/$bundleId'
      fullPath: '/publisher/bundles/$bundleId'
      preLoaderRoute: typeof PublisherBundlesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/titles/new': {
      id: '/pb-admin/titles/new'
      path: '/pb-admin/titles/new'
      fullPath: '/pb-admin/titles/new'
      preLoaderRoute: typeof PbAdminTitlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/titles/$bookId': {
      id: '/pb-admin/titles/$bookId'
      path: '/pb-admin/titles/$bookId'
      fullPath: '/pb-admin/titles/$bookId'
      preLoaderRoute: typeof PbAdminTitlesBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/publishers-authors/$id': {
      id: '/pb-admin/publishers-authors/$id'
      path: '/$id'
      fullPath: '/pb-admin/publishers-authors/$id'
      preLoaderRoute: typeof PbAdminPublishersAuthorsIdRouteImport
      parentRoute: typeof PbAdminPublishersAuthorsRoute
    }
    '/pb-admin/commission-rates_/$id': {
      id: '/pb-admin/commission-rates_/$id'
      path: '/pb-admin/commission-rates/$id'
      fullPath: '/pb-admin/commission-rates/$id'
      preLoaderRoute: typeof PbAdminCommissionRatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/bundles/new': {
      id: '/pb-admin/bundles/new'
      path: '/pb-admin/bundles/new'
      fullPath: '/pb-admin/bundles/new'
      preLoaderRoute: typeof PbAdminBundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/bundles/$bundleId': {
      id: '/pb-admin/bundles/$bundleId'
      path: '/pb-admin/bundles/$bundleId'
      fullPath: '/pb-admin/bundles/$bundleId'
      preLoaderRoute: typeof PbAdminBundlesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/author-management/$authorId': {
      id: '/pb-admin/author-management/$authorId'
      path: '/$authorId'
      fullPath: '/pb-admin/author-management/$authorId'
      preLoaderRoute: typeof PbAdminAuthorManagementAuthorIdRouteImport
      parentRoute: typeof PbAdminAuthorManagementRoute
    }
  }
}

interface PbAdminAuthorManagementRouteChildren {
  PbAdminAuthorManagementAuthorIdRoute: typeof PbAdminAuthorManagementAuthorIdRoute
}

const PbAdminAuthorManagementRouteChildren: PbAdminAuthorManagementRouteChildren =
  {
    PbAdminAuthorManagementAuthorIdRoute: PbAdminAuthorManagementAuthorIdRoute,
  }

const PbAdminAuthorManagementRouteWithChildren =
  PbAdminAuthorManagementRoute._addFileChildren(
    PbAdminAuthorManagementRouteChildren,
  )

interface PbAdminPublishersAuthorsRouteChildren {
  PbAdminPublishersAuthorsIdRoute: typeof PbAdminPublishersAuthorsIdRoute
}

const PbAdminPublishersAuthorsRouteChildren: PbAdminPublishersAuthorsRouteChildren =
  {
    PbAdminPublishersAuthorsIdRoute: PbAdminPublishersAuthorsIdRoute,
  }

const PbAdminPublishersAuthorsRouteWithChildren =
  PbAdminPublishersAuthorsRoute._addFileChildren(
    PbAdminPublishersAuthorsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryUserRoute: LibraryUserRoute,
  NotificationsRoute: NotificationsRoute,
  LibraryAdminBannersRoute: LibraryAdminBannersRoute,
  LibraryAdminCartRoute: LibraryAdminCartRoute,
  LibraryAdminCatalogueRoute: LibraryAdminCatalogueRoute,
  LibraryAdminCoursesRoute: LibraryAdminCoursesRoute,
  LibraryAdminDepartmentsRoute: LibraryAdminDepartmentsRoute,
  LibraryAdminManageEbooksRoute: LibraryAdminManageEbooksRoute,
  LibraryAdminOrdersRoute: LibraryAdminOrdersRoute,
  LibraryAdminReportsRoute: LibraryAdminReportsRoute,
  LibraryAdminRequestsRoute: LibraryAdminRequestsRoute,
  LibraryAdminSupportRoute: LibraryAdminSupportRoute,
  LibraryAdminUsersRoute: LibraryAdminUsersRoute,
  PbAdminAdminUsersRoute: PbAdminAdminUsersRoute,
  PbAdminAuthorManagementRoute: PbAdminAuthorManagementRouteWithChildren,
  PbAdminCategoriesRoute: PbAdminCategoriesRoute,
  PbAdminCommissionRatesRoute: PbAdminCommissionRatesRoute,
  PbAdminCustomersRoute: PbAdminCustomersRoute,
  PbAdminMarginReportRoute: PbAdminMarginReportRoute,
  PbAdminMergeAuthorsRoute: PbAdminMergeAuthorsRoute,
  PbAdminPromoCodesRoute: PbAdminPromoCodesRoute,
  PbAdminPublishersAuthorsRoute: PbAdminPublishersAuthorsRouteWithChildren,
  PbAdminSalesReportRoute: PbAdminSalesReportRoute,
  PublisherBankAccountsRoute: PublisherBankAccountsRoute,
  PublisherMarginReportRoute: PublisherMarginReportRoute,
  PublisherProfileRoute: PublisherProfileRoute,
  PublisherSalesReportRoute: PublisherSalesReportRoute,
  PublisherSettingsRoute: PublisherSettingsRoute,
  PublisherSupportRoute: PublisherSupportRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  LibraryAdminIndexRoute: LibraryAdminIndexRoute,
  PbAdminIndexRoute: PbAdminIndexRoute,
  PublisherIndexRoute: PublisherIndexRoute,
  PbAdminBundlesBundleIdRoute: PbAdminBundlesBundleIdRoute,
  PbAdminBundlesNewRoute: PbAdminBundlesNewRoute,
  PbAdminCommissionRatesIdRoute: PbAdminCommissionRatesIdRoute,
  PbAdminTitlesBookIdRoute: PbAdminTitlesBookIdRoute,
  PbAdminTitlesNewRoute: PbAdminTitlesNewRoute,
  PublisherBundlesBundleIdRoute: PublisherBundlesBundleIdRoute,
  PublisherBundlesNewRoute: PublisherBundlesNewRoute,
  PublisherCatalogueImportFileNameRoute: PublisherCatalogueImportFileNameRoute,
  PublisherCatalogueImportNewRoute: PublisherCatalogueImportNewRoute,
  PublisherCatalogueBookIdRoute: PublisherCatalogueBookIdRoute,
  PublisherCatalogueNewRoute: PublisherCatalogueNewRoute,
  PublisherPromoCodesNewRoute: PublisherPromoCodesNewRoute,
  PbAdminBundlesIndexRoute: PbAdminBundlesIndexRoute,
  PbAdminTitlesIndexRoute: PbAdminTitlesIndexRoute,
  PublisherBundlesIndexRoute: PublisherBundlesIndexRoute,
  PublisherCatalogueImportIndexRoute: PublisherCatalogueImportIndexRoute,
  PublisherCatalogueIndexRoute: PublisherCatalogueIndexRoute,
  PublisherPromoCodesIndexRoute: PublisherPromoCodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
