/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SalesReportRouteImport } from './routes/sales-report'
import { Route as PromoCodesRouteImport } from './routes/promo-codes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarginReportRouteImport } from './routes/margin-report'
import { Route as CatalogueImportRouteImport } from './routes/catalogue-import'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoCodesNewRouteImport } from './routes/promo-codes_.new'
import { Route as CatalogueNewRouteImport } from './routes/catalogue_.new'
import { Route as CatalogueBookIdRouteImport } from './routes/catalogue_.$bookId'
import { Route as CatalogueImportNewRouteImport } from './routes/catalogue-import_.new'
import { Route as CatalogueImportFileNameRouteImport } from './routes/catalogue-import_.$fileName'
import { Route as BundlesNewRouteImport } from './routes/bundles_.new'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReportRoute = SalesReportRouteImport.update({
  id: '/sales-report',
  path: '/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoCodesRoute = PromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginReportRoute = MarginReportRouteImport.update({
  id: '/margin-report',
  path: '/margin-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueImportRoute = CatalogueImportRouteImport.update({
  id: '/catalogue-import',
  path: '/catalogue-import',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoCodesNewRoute = PromoCodesNewRouteImport.update({
  id: '/promo-codes_/new',
  path: '/promo-codes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueNewRoute = CatalogueNewRouteImport.update({
  id: '/catalogue_/new',
  path: '/catalogue/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueBookIdRoute = CatalogueBookIdRouteImport.update({
  id: '/catalogue_/$bookId',
  path: '/catalogue/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueImportNewRoute = CatalogueImportNewRouteImport.update({
  id: '/catalogue-import_/new',
  path: '/catalogue-import/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueImportFileNameRoute = CatalogueImportFileNameRouteImport.update({
  id: '/catalogue-import_/$fileName',
  path: '/catalogue-import/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesNewRoute = BundlesNewRouteImport.update({
  id: '/bundles_/new',
  path: '/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/bundles': typeof BundlesRoute
  '/catalogue': typeof CatalogueRoute
  '/catalogue-import': typeof CatalogueImportRoute
  '/margin-report': typeof MarginReportRoute
  '/notifications': typeof NotificationsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/sales-report': typeof SalesReportRoute
  '/support': typeof SupportRoute
  '/bundles/new': typeof BundlesNewRoute
  '/catalogue-import/$fileName': typeof CatalogueImportFileNameRoute
  '/catalogue-import/new': typeof CatalogueImportNewRoute
  '/catalogue/$bookId': typeof CatalogueBookIdRoute
  '/catalogue/new': typeof CatalogueNewRoute
  '/promo-codes/new': typeof PromoCodesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/bundles': typeof BundlesRoute
  '/catalogue': typeof CatalogueRoute
  '/catalogue-import': typeof CatalogueImportRoute
  '/margin-report': typeof MarginReportRoute
  '/notifications': typeof NotificationsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/sales-report': typeof SalesReportRoute
  '/support': typeof SupportRoute
  '/bundles/new': typeof BundlesNewRoute
  '/catalogue-import/$fileName': typeof CatalogueImportFileNameRoute
  '/catalogue-import/new': typeof CatalogueImportNewRoute
  '/catalogue/$bookId': typeof CatalogueBookIdRoute
  '/catalogue/new': typeof CatalogueNewRoute
  '/promo-codes/new': typeof PromoCodesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/bundles': typeof BundlesRoute
  '/catalogue': typeof CatalogueRoute
  '/catalogue-import': typeof CatalogueImportRoute
  '/margin-report': typeof MarginReportRoute
  '/notifications': typeof NotificationsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/sales-report': typeof SalesReportRoute
  '/support': typeof SupportRoute
  '/bundles_/new': typeof BundlesNewRoute
  '/catalogue-import_/$fileName': typeof CatalogueImportFileNameRoute
  '/catalogue-import_/new': typeof CatalogueImportNewRoute
  '/catalogue_/$bookId': typeof CatalogueBookIdRoute
  '/catalogue_/new': typeof CatalogueNewRoute
  '/promo-codes_/new': typeof PromoCodesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-accounts'
    | '/bundles'
    | '/catalogue'
    | '/catalogue-import'
    | '/margin-report'
    | '/notifications'
    | '/promo-codes'
    | '/sales-report'
    | '/support'
    | '/bundles/new'
    | '/catalogue-import/$fileName'
    | '/catalogue-import/new'
    | '/catalogue/$bookId'
    | '/catalogue/new'
    | '/promo-codes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-accounts'
    | '/bundles'
    | '/catalogue'
    | '/catalogue-import'
    | '/margin-report'
    | '/notifications'
    | '/promo-codes'
    | '/sales-report'
    | '/support'
    | '/bundles/new'
    | '/catalogue-import/$fileName'
    | '/catalogue-import/new'
    | '/catalogue/$bookId'
    | '/catalogue/new'
    | '/promo-codes/new'
  id:
    | '__root__'
    | '/'
    | '/bank-accounts'
    | '/bundles'
    | '/catalogue'
    | '/catalogue-import'
    | '/margin-report'
    | '/notifications'
    | '/promo-codes'
    | '/sales-report'
    | '/support'
    | '/bundles_/new'
    | '/catalogue-import_/$fileName'
    | '/catalogue-import_/new'
    | '/catalogue_/$bookId'
    | '/catalogue_/new'
    | '/promo-codes_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankAccountsRoute: typeof BankAccountsRoute
  BundlesRoute: typeof BundlesRoute
  CatalogueRoute: typeof CatalogueRoute
  CatalogueImportRoute: typeof CatalogueImportRoute
  MarginReportRoute: typeof MarginReportRoute
  NotificationsRoute: typeof NotificationsRoute
  PromoCodesRoute: typeof PromoCodesRoute
  SalesReportRoute: typeof SalesReportRoute
  SupportRoute: typeof SupportRoute
  BundlesNewRoute: typeof BundlesNewRoute
  CatalogueImportFileNameRoute: typeof CatalogueImportFileNameRoute
  CatalogueImportNewRoute: typeof CatalogueImportNewRoute
  CatalogueBookIdRoute: typeof CatalogueBookIdRoute
  CatalogueNewRoute: typeof CatalogueNewRoute
  PromoCodesNewRoute: typeof PromoCodesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-report': {
      id: '/sales-report'
      path: '/sales-report'
      fullPath: '/sales-report'
      preLoaderRoute: typeof SalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-codes': {
      id: '/promo-codes'
      path: '/promo-codes'
      fullPath: '/promo-codes'
      preLoaderRoute: typeof PromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin-report': {
      id: '/margin-report'
      path: '/margin-report'
      fullPath: '/margin-report'
      preLoaderRoute: typeof MarginReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue-import': {
      id: '/catalogue-import'
      path: '/catalogue-import'
      fullPath: '/catalogue-import'
      preLoaderRoute: typeof CatalogueImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-codes_/new': {
      id: '/promo-codes_/new'
      path: '/promo-codes/new'
      fullPath: '/promo-codes/new'
      preLoaderRoute: typeof PromoCodesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue_/new': {
      id: '/catalogue_/new'
      path: '/catalogue/new'
      fullPath: '/catalogue/new'
      preLoaderRoute: typeof CatalogueNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue_/$bookId': {
      id: '/catalogue_/$bookId'
      path: '/catalogue/$bookId'
      fullPath: '/catalogue/$bookId'
      preLoaderRoute: typeof CatalogueBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue-import_/new': {
      id: '/catalogue-import_/new'
      path: '/catalogue-import/new'
      fullPath: '/catalogue-import/new'
      preLoaderRoute: typeof CatalogueImportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue-import_/$fileName': {
      id: '/catalogue-import_/$fileName'
      path: '/catalogue-import/$fileName'
      fullPath: '/catalogue-import/$fileName'
      preLoaderRoute: typeof CatalogueImportFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles_/new': {
      id: '/bundles_/new'
      path: '/bundles/new'
      fullPath: '/bundles/new'
      preLoaderRoute: typeof BundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankAccountsRoute: BankAccountsRoute,
  BundlesRoute: BundlesRoute,
  CatalogueRoute: CatalogueRoute,
  CatalogueImportRoute: CatalogueImportRoute,
  MarginReportRoute: MarginReportRoute,
  NotificationsRoute: NotificationsRoute,
  PromoCodesRoute: PromoCodesRoute,
  SalesReportRoute: SalesReportRoute,
  SupportRoute: SupportRoute,
  BundlesNewRoute: BundlesNewRoute,
  CatalogueImportFileNameRoute: CatalogueImportFileNameRoute,
  CatalogueImportNewRoute: CatalogueImportNewRoute,
  CatalogueBookIdRoute: CatalogueBookIdRoute,
  CatalogueNewRoute: CatalogueNewRoute,
  PromoCodesNewRoute: PromoCodesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
